# Generated by Django 5.0.3 on 2024-05-02 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEstoque', '0002_cliente_remove_produto_categoria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutosInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produtos_count', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(choices=[('PP', 'pp'), ('GG', 'gg'), ('P', 'p'), ('XG', 'xg'), ('M', 'm'), ('G', 'g')], default='', max_length=2),
        ),
    ]
