# Generated by Django 5.0.3 on 2024-04-04 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEstoque', '0002_remove_produto_imagem_produto_descricao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('data_compra', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
