# Generated by Django 5.0.3 on 2024-04-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appEstoque', '0002_cliente_remove_produto_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tamanho',
            field=models.CharField(choices=[('GG', 'gg'), ('PP', 'pp'), ('M', 'm'), ('XG', 'xg'), ('P', 'p'), ('G', 'g')], default='', max_length=2),
        ),
    ]
