# Generated by Django 5.0.3 on 2024-04-04 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appEstoque', '0003_venda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='pub_date',
            new_name='data_publicacao',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='content',
            new_name='descricao',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='title',
            new_name='titulo',
        ),
    ]
